config/routes.rb
Rails.application.routes.draw do
  root 'tests#dashboard'
  resources :tests, only: [] do
    get   'patient/:id/created', to: "patients#created", as: :created_patient
    resources :patients,              only: [:new, :create]
  end
  #get 'patients/new'
  #get 'patients/create'
  #get 'patients/created'
  #get 'tests/dashboard'
  # Routes for devise
  # Doctors
  devise_for :doctors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/control_group.rb
class ControlGroup < ApplicationRecord
  # Associations
  belongs_to  :test
  has_many    :patients

  # Validations
  validates :name, :person_limit, presence: true
  validates :person_limit,  numericality: { only_integer: true, greater_than_or_equal_to: 0}
  validates :margin_diff,   numericality: { only_integer: true, greater_than_or_equal_to: 0}, allow_nil: true

  # Callbacks

  # Scopes
  scope :count_patients_by_test, -> (test_id) { select(:id, "count(patients.id) count", :margin_diff).left_outer_joins(:patients).group(:id).order(count: :desc) }

  # Functions
  def self.random_assign test_id
    cgs = self.where(test_id: test_id)
    count_cg = Patient.control_group_count(cgs.pluck(:id))
    cg_margin = cgs.first.margin_diff
    raise count_cg.inspect
  end
end

app/models/covid.rb
class Covid < ApplicationRecord
  # Associations
  has_many :historical_clinical_patients

  # Validations
  validates :name, presence: true
end

app/models/destiny.rb
class Destiny < ApplicationRecord
  # Associations
  has_many :historical_clinical_patients

  # Validations
  validates :name, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :timeoutable

  # Relations
  has_many :test_role_doctors
  has_many :roles, through: :test_role_doctors

  # Callbacks

  # Validations
  validates :email, :name, :ape_pat, :ape_mat, presence: true
  validates :email, uniqueness: true


  # Instance functions
  def full_name
    [name, ape_pat, ape_mat].join(" ").strip
  end
end

app/models/hosp_motive.rb
class HospMotive < ApplicationRecord
  # Associations
  has_many :historical_clinical_patients

  # Validations
  validates :name, presence: true
end

app/models/illness.rb
class Illness < ApplicationRecord
  # Associations
  has_and_belongs_to_many :historical_clinical_patients

  # Validations
  validates :name, presence: true
end

app/models/job.rb
class Job < ApplicationRecord
  # Associations
  has_many :patients
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Relations
  belongs_to :job
  belongs_to :control_group
  has_many :historical_clinical_patients,   inverse_of: :patient
  has_many :historical_laboratory_patients, inverse_of: :patient
  accepts_nested_attributes_for :historical_clinical_patients
  accepts_nested_attributes_for :historical_laboratory_patients

  # Enums
  enum gender:    { femenino: 0, masculino: 1 }, _prefix: :genero
  enum persalud:  { no: 0, si: 1 }

  # Virtual variables
  attr_accessor :test_id

  # Validations
  validates :phone, :email, :birthdate, :weight, :height, presence: true
	validates :phone, :contact_phone, uniqueness: true, format: { with: /\d{10}/, message: "No parece ser un número telefónico"}
	validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "No es un correo válido" }
	validates :weight, :height, numericality: {only_integers: true, greater_than: 0}

  # Scopes
  scope :with_age, -> { select("*, date_part('year', age(birthdate))::integer age") }

  #  Callbacks
  before_validation :assign_control_group
  after_create_commit :send_welcome_message
  after_update_commit :send_welcome_message

  # Functions
  def assign_control_group
    if control_group_id
      return
    end

    self.control_group_id    = determine_control_group(test_id)
  end

  private
  def determine_control_group test_id
    patients_by_control_group   = ControlGroup.count_patients_by_test(test_id)
    control_group_margin_diff   = patients_by_control_group.first.margin_diff
    min_patients_on_cg          = patients_by_control_group.last.count

    control_groups_candidates = patients_by_control_group.map{ |cg| cg.id if (cg.count - min_patients_on_cg) < control_group_margin_diff }.compact

    return control_groups_candidates.sample
  end

  def send_welcome_message
    begin
      a = TwilioClient.new
      a.send_whatsapp_text(self.phone, message_text(self.name))
      logger.debug {a.inspect}
    rescue StandardError => e
      logger.debug{e.message}
    end
  end

  def message_text nombre
    "Bienvenido #{nombre}!, por favor, actualiza tu información cada 24 hrs. Saludos!"
  end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/secondary_effect.rb
class SecondaryEffect < ApplicationRecord
  # Associations
  has_and_belongs_to_many :historical_clinical_patients

  # Validations
  validates :name, presence: true
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  # Associations
  has_and_belongs_to_many :historical_clinical_patients

  # Validations
  validates :name, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  # Relations
  has_many :control_groups
  has_many :test_role_doctors
  has_many :doctors, through: :text_role_doctors
end

app/models/test_role_doctor.rb
class TestRoleDoctor < ApplicationRecord
  belongs_to :test
  belongs_to :doctor
  belongs_to :role
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  # Associations
  has_many :historical_clinical_patients

  # Validations
  validates :name, presence: true
end

app/models/treatment_adherence.rb
class TreatmentAdherence < ApplicationRecord
  # Associations
  has_many :historical_clinical_patients

  # Validations
  validates :name, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ensayo Clínico</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="flex flex-col justify-between min-h-screen">
    <%= render 'partials/header' %>
    <div class="font-body font-light">
      <%= yield %>
    </div>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_alerts.html.erb
<% if notice %>
  <p class="notice"><i class="fa fa-exclamation-circle mr-2"></i><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><i class="far fa-times-circle mr-2"></i><%= alert %></p>
<% end %>

app/views/partials/_footer.html.erb
<footer>
  <a href="#">Aviso de privacidad</a>
  <a href="#">Contáctanos</a>
  <a href="#">Términos y condiciones</a>
  <div class="social-networks">
    <a href="#" text="Cuenta oficial de Facebook"><i class="fab fa-facebook-f"></i></a>
    <a href="#" text="Cuenta oficial de Twitter"><i class="fab fa-twitter"></i></a>
    <a href="#" text="Cuenta oficial de Instagram"><i class="fab fa-instagram"></i></a>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="text-center">
  <div class="py-2 flex justify-center items-center bg-brand-orange text-xl sm:text-4xl text-white font-bold">
    <i class="fa fa-viruses mr-1"></i>
    <h1><%= defined?(title) ? title : "Ensayo Clínico" %></h1>
    <i class="fa fa-viruses ml-1"></i>
  </div>
  <% unless controller_name.eql?("sessions") %>
    <% if doctor_signed_in?%>
      <%= link_to "cerrar sesión", destroy_doctor_session_path, method: :delete, class: "text-red-600 float-right mr-4" %>
    <% else %>
      <%= link_to "iniciar sesión", new_doctor_session_path, class: "text-blue-500 float-right mr-4" %>
    <% end %>
    <br>
  <% end %>
  <%= render 'partials/alerts' %>
</header>