config/routes.rb
Rails.application.routes.draw do
  root 'tests#dashboard'
  resources :tests, only: [] do
    get   'patient/:id/created', to: "patients#created", as: :created_patient
    resources :patients,              only: [:new, :create]
  end
  #get 'patients/new'
  #get 'patients/create'
  #get 'patients/created'
  #get 'tests/dashboard'
  # Routes for devise
  # Doctors
  devise_for :doctors
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Relations
  belongs_to :job
  belongs_to :control_group
  has_many :historical_clinical_patients,   inverse_of: :patient
  has_many :historical_laboratory_patients, inverse_of: :patient
  accepts_nested_attributes_for :historical_clinical_patients
  accepts_nested_attributes_for :historical_laboratory_patients

  # Enums
  enum gender:    { femenino: 0, masculino: 1 }, _prefix: :genero
  enum persalud:  { no: 0, si: 1 }

  # Virtual variables
  attr_accessor :test_id

  # Validations
  validates :phone, :email, :birthdate, :weight, :height, presence: true
	validates :phone, :contact_phone, uniqueness: true, format: { with: /\d{10}/, message: "No parece ser un número telefónico"}
	validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "No es un correo válido" }
	validates :weight, :height, numericality: {only_integers: true, greater_than: 0}

  # Scopes
  scope :with_age, -> { select("*, date_part('year', age(birthdate))::integer age") }

  #  Callbacks
  before_validation :assign_control_group
  after_create_commit :send_welcome_message
  after_update_commit :send_welcome_message

  # Functions
  def assign_control_group
    if control_group_id
      return
    end

    self.control_group_id    = determine_control_group(test_id)
  end

  private
  def determine_control_group test_id
    patients_by_control_group   = ControlGroup.count_patients_by_test(test_id)
    control_group_margin_diff   = patients_by_control_group.first.margin_diff
    min_patients_on_cg          = patients_by_control_group.last.count

    control_groups_candidates = patients_by_control_group.map{ |cg| cg.id if (cg.count - min_patients_on_cg) < control_group_margin_diff }.compact

    return control_groups_candidates.sample
  end

  def send_welcome_message
    begin
      a = TwilioClient.new
      a.send_whatsapp_text(self.phone, message_text(self.name))
      logger.debug {a.inspect}
    rescue StandardError => e
      logger.debug{e.message}
    end
  end

  def message_text nombre
    "Bienvenido #{nombre}!, por favor, actualiza tu información cada 24 hrs. Saludos!"
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # Callbacks
  before_action :get_test
  before_action :get_patient_by_phone, only: [:create]
  before_action :get_patient, only: [:created]
  before_action :authenticate_doctor!, only: [:new, :create, :created]

  # Actions
  def new
    @patient = Patient.new
    @patient.historical_clinical_patients.build
    @patient.historical_laboratory_patients.build
  end

  def create
    @patient = Patient.new(patient_params) unless @patient
    @patient.test_id = @test.id

    if @patient.save
      @patient.historical_clinical_patients.create!(historical_clinical_patient_params)
      @patient.historical_laboratory_patients.create!(historical_laboratory_patient_params)
      redirect_to test_created_patient_path(test_id: @test.id, id: @patient.id)
    else
      render :new
    end
  end

  def created
  end

  private
  def get_test
    @test = Test.find(params[:test_id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "Ensayo no encontrado, ¿Está escrito de manera correcta?."
    redirect_to root_path
  end

  def get_patient
    @patient = Patient.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "Paciente no encontrado, ¿Está correctamente escrita la URL?."
    redirect_to root_path
  end

  def get_patient_by_phone
    @patient = Patient.find_by(phone: patient_phone_params[:phone])
  end

  def patient_phone_params
    params.require(:patient).permit(:phone)
  end

  def patient_params
    params.require(:patient).permit(:name, :email, :nss, :address, :postal_code, :phone, :birthdate, :contact_phone, :job_id, :persalud, :gender, :weight, :height)
  end

  def historical_clinical_patient_params
    params.require(:patient).
      require(:historical_clinical_patients_attributes).
      require("0").
      permit(:fc, :fr, :sato2, :pas, :pad, :temp, :covid_id, :treatment_id, :destiny_id, :destiny_date, :hosp_motive_id, :esthosp, :estuci, :treatment_adherence_id, secondary_effect_ids: [], illness_ids: [], symptom_ids: [])
  end

  def historical_laboratory_patient_params
    params.require(:patient).require(:historical_laboratory_patients_attributes).require("0").permit(:eritr, :hb, :vgm, :cmhb, :plaq, :vpm, :leuct, :neutrt, :neutrsegm, :neutrb, :metamiel, :promiel, :blast, :eosin, :monoc, :linf, :gluc, :bun, :urea, :dimer, :il6, :tnf, :ogf)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_clinical_form.html.erb
<%= f.fields_for :historical_clinical_patients do |fcp| %>
  <div class="container mt-8">
    <div class="flex justify-center text-center">
      <h2 class="text-xl md:text-2xl lg:text-3xl text-brand-gray-darker font-medium">
        <i class="fas fa-notes-medical mr-2"></i>
        Información Clínica
      </h2>
    </div>
    <div class="form block">
      <div class="question">
        <p>Enfermedades previas</p>
        <div class="form-control">
          <%= fcp.collection_check_boxes :illness_ids, Illness.where.not(id: 1), :id, :name %>
        </div>
      </div>
      <div class="question">
        <p>Síntomas que presenta el paciente</p>
        <div class="form-control">
          <%= fcp.collection_check_boxes :symptom_ids, Symptom.where.not(id: 1), :id, :name %>
        </div>
      </div>
    </div>
    <div class="form">
      <div class="form-control">
        <%= fcp.label :fc, "Frecuencia cardiaca" %>
        <%= fcp.number_field :fc, min: 0 %>
        <small>por minuto</small>
      </div>
      <div class="form-control">
        <%= fcp.label :fr, "Frecuencia respiratoria" %>
        <%= fcp.number_field :fr, min: 0 %>
        <small>por minuto</small>
      </div>
      <div class="form-control">
        <%= fcp.label :sato2, "Hemoglobina saturada con oxíteno" %>
        <%= fcp.number_field :sato2, min: 0, max: 100 %>
        <small>Porcentaje</small>
      </div>
      <div class="form-control">
        <%= fcp.label :pas, "Presión arterial sistólica" %>
        <%= fcp.text_field :pas %>
      </div>
      <div class="form-control">
        <%= fcp.label :pad, "Presión arterial diastólica" %>
        <%= fcp.text_field :pad %>
      </div>
      <div class="form-control">
        <%= fcp.label :temp, "Temperatura axilar" %>
        <%= fcp.number_field :temp, min: 0, step: 0.1 %>
        <small>en grados celsius</small>
      </div>
      <div class="form-control">
        <%= fcp.label :covid_id, "Prueba COVID-19" %>
        <%= fcp.collection_select :covid_id, Covid.all, :id, :name, prompt: "Seleccione una opción" %>
      </div>
      <div class="form-control">
        <%= fcp.label :treatment_id, "Tratamiento" %>
        <%= fcp.collection_select :treatment_id, Treatment.all, :id, :name, prompt: "Seleccione una opción" %>
      </div>
      <div class="form-control">
        <%= fcp.label :destiny_id, "Destino" %>
        <%= fcp.collection_select :destiny_id, Destiny.all, :id, :name, prompt: "Seleccione una opción" %>
      </div>
      <div class="form-control">
        <%= fcp.label :destiny_date, "Fecha destino" %>
        <%= fcp.date_field :destiny_date %>
      </div>
      <div class="form-control">
        <%= fcp.label :hosp_motive_id, "Motivo de Hospitalización" %>
        <%= fcp.collection_select :hosp_motive_id, HospMotive.all, :id, :name, prompt: "Seleccione una opción" %>
      </div>
      <div class="form-control">
        <%= fcp.label :esthosp, "Estancia hospitalaria en piso" %>
        <%= fcp.number_field :esthosp, min: 0 %>
        <small>en días</small>
      </div>
      <div class="form-control">
        <%= fcp.label :estuci, "Estancia en UCI" %>
        <%= fcp.number_field :estuci, min: 0 %>
        <small>en días</small>
      </div>
    </div>
    <div class="form block">
      <div class="question">
        <p>Effectos secundarios</p>
        <div class="form-control">
          <%= fcp.collection_check_boxes :secondary_effect_ids, SecondaryEffect.where.not(id: 1), :id, :name %>
        </div>
      </div>
      <div class="form-control">
        <%= fcp.label :treatment_adherence_id, "Adherencia al tratamiento" %>
        <%= fcp.collection_select :treatment_adherence_id, TreatmentAdherence.all, :id, :name, prompt: "Seleccione una opción" %>
      </div>
    </div>
  </div>
<% end %>

app/views/patients/_form.html.erb
<%= form_with(model: @patient, url: test_patients_path(test_id: @test.id), local: true) do |f| %>
  <div class="container mt-8">
    <div class="flex justify-center text-center">
      <h1 class="text-2xl md:text-3xl lg:text-4xl text-brand-gray-darker font-medium"><i class="fa fa-address-card mr-2"></i>Datos personales</h1>
    </div>
    <div class="form">
      <div class="form-control">
        <%= f.label :name, "Nombre*" %>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="form-control">
        <%= f.label :email, "Correo electrónico*" %>
        <%= f.email_field :email, required: true %>
      </div>
      <div class="form-control">
        <label for="">Fecha</label>
        <input type="date" value="<%= Date.today %>" disabled readonly>
      </div>
      <div class="form-control">
        <%= f.label :nss, "Número de Seguridad Social*" %>
        <%= f.text_field :nss, required: true, pattern: "\\d{8}" %>
        <small>8 dígitos</small>
      </div>
      <div class="form-control">
        <%= f.label :address, "Domicilio*" %>
        <%= f.text_field :address, required: true %>
      </div>
      <div class="form-control">
        <%= f.label :postal_code, "Código Postal*" %>
        <%= f.number_field :postal_code, required: true, pattern: "\\d{5}" %>
        <small>5 dígitos</small>
      </div>
      <div class="form-control">
        <%= f.label :phone, "Teléfono celular*" %>
        <%= f.text_field :phone, required: true, pattern: "\\d{10}" %>
        <small>10 dígitos</small>
      </div>
      <div class="form-control">
        <%= f.label :birthdate, "Fecha de cumpleaños*" %>
        <%= f.date_field :birthdate, required: true %>
      </div>
      <div class="form-control">
        <%= f.label :contact_phone, "Teléfono de un contacto*" %>
        <%= f.text_field :contact_phone, required: true, pattern: "\\d{10}" %>
        <small>10 dígitos</small>
      </div>
      <div class="form-control">
        <%= f.label :job_id, "Ocupación*" %>
        <%= f.collection_select :job_id, Job.all, :id, :name, required: true, prompt: "Seleccione una opción" %>
      </div>
      <div class="form-control">
        <%= f.label :gender, "Sexo*" %>
        <%= f.select :gender, Patient.genders.map { |key, val| [key.capitalize, key] }, { required: true, include_blank: "Selecciona una opcion" } %>
      </div>
      <div class="form-control">
        <%= f.label :weight, "Peso*" %>
        <%= f.number_field :weight, required: true, min: 0, max: 300, step: 0.01 %>
        <small>en kilogramos</small>
      </div>
      <div class="form-control">
        <%= f.label :height, "Talla*" %>
        <%= f.number_field :height, required: true, min: 0, max: 300, step: 0.01 %>
        <small>en metros</small>
      </div>
      <div class="form-control">
        <%= f.label :persalud, "Personal de salud en contacto con COVID*" %>
        <%= f.select :persalud, Patient.persaluds.map { |key, val| [key.capitalize, key] }, { required: true, include_blank: "Selecciona una opcion" } %>
      </div>
    </div>
  </div>
  <%= render 'clinical_form',     f: f %>
  <%= render 'laboratory_form',   f: f %>
  <div class="flex justify-around">
    <button type="submit">
      <p>Dar de alta</p>
      <div class="icon">
        <i class="fa fa-eye"></i>
      </div>
    </button>
  </div>
<% end %>

app/views/patients/_laboratory_form.html.erb
<%= f.fields_for :historical_laboratory_patients do |flp| %>
  <div class="container mt-8">
    <div class="flex justify-center text-center">
      <h2 class="text-xl md:text-2xl lg:text-3xl text-brand-gray-darker font-medium"><i class="fas fa-prescription-bottle-alt mr-2"></i>Información de laboratorio</h2>
    </div>
    <div class="form">
      <div class="form-control"><%= flp.label :eritr, "Eritrocitos" %><%= flp.text_field :eritr %></div>
      <div class="form-control"><%= flp.label :hb, "Hemoglobina" %><%= flp.text_field :hb %></div>
      <div class="form-control"><%= flp.label :vgm, "Volumen globular medio" %><%= flp.text_field :vgm %></div>
      <div class="form-control"><%= flp.label :cmhb, "Conc. Media hb" %><%= flp.text_field :cmhb %></div>
      <div class="form-control"><%= flp.label :plaq, "Plaquetas" %><%= flp.text_field :plaq %></div>
      <div class="form-control"><%= flp.label :vpm, "Volumen plaquetario medio" %><%= flp.text_field :vpm %></div>
      <div class="form-control"><%= flp.label :leuct, "Leucocitos totales" %><%= flp.text_field :leuct %></div>
      <div class="form-control"><%= flp.label :neutrt, "Neutrófilos totales" %><%= flp.text_field :neutrt %></div>
      <div class="form-control"><%= flp.label :neutrsegm, "Nutrófilos Segmentados" %><%= flp.text_field :neutrsegm %></div>
      <div class="form-control"><%= flp.label :neutrb, "Neutrófilos en banda" %><%= flp.text_field :neutrb %></div>
      <div class="form-control"><%= flp.label :metamiel, "Metamielocitos" %><%= flp.text_field :metamiel %></div>
      <div class="form-control"><%= flp.label :promiel, "Promielocitos" %><%= flp.text_field :promiel %></div>
      <div class="form-control"><%= flp.label :blast, "Blastos" %><%= flp.text_field :blast %></div>
      <div class="form-control"><%= flp.label :eosin, "Eosinófilos" %><%= flp.text_field :eosin %></div>
      <div class="form-control"><%= flp.label :monoc, "Monocitos" %><%= flp.text_field :monoc %></div>
      <div class="form-control"><%= flp.label :linf, "Linfocitos" %><%= flp.text_field :linf %></div>
      <div class="form-control"><%= flp.label :gluc, "Glucosa" %><%= flp.text_field :gluc %></div>
      <div class="form-control"><%= flp.label :bun, "Nitrógeno uréico sérico" %><%= flp.text_field :bun %></div>
      <div class="form-control"><%= flp.label :urea, "Urea sérica" %><%= flp.text_field :urea %></div>
      <div class="form-control"><%= flp.label :dimer, "Dímeros D" %><%= flp.text_field :dimer %></div>
      <div class="form-control"><%= flp.label :il6, "Interleucina 6" %><%= flp.text_field :il6 %></div>
      <div class="form-control"><%= flp.label :tnf, "Factor de necrosis tumoral alfa" %><%= flp.text_field :tnf %></div>
      <div class="form-control"><%= flp.label :ogf, "Factor de crecimiento opioide" %><%= flp.text_field :ogf %></div>
    </div>
  </div>
<% end %>

app/views/patients/create.html.erb
<h1>Patients#create</h1>
<p>Find me in app/views/patients/create.html.erb</p>

app/views/patients/created.html.erb
<div class="card gradient">
  <div class="card-header-circular bg-brand-orange">
    <div class="rounded-full border-4 border-white py-2 px-3">
      <i class="fas fa-user-check"></i>
    </div>
  </div>
  <div class="card-body">
    <h3 class="text-xl">Gracias por tu participación.</h3>
    <p>Paciente registrado y asignado a un bazo de control de manera aleatoria.</p>
  </div>
</div>
<div class="alert-card">
  <i class="fas fa-exclamation-triangle"></i>
  <p>Por favor indique al paciente que debe actualizar su información a través del <b>Diario del paciente</b> cada 24 hrs.</p>
</div>
<div class="flex justify-around">
  <button onclick="Turbolinks.visit('<%= root_path %>')"><p>Volver a la pantalla principal</p><div class="icon"><i class="fas fa-home"></i></div></button>
  <button onclick="Turbolinks.visit('<%= new_test_patient_path(test_id: @test.id) %>')"><p>Registrar un nuevo paciente</p><div class="icon"><i class="fas fa-user-plus"></i></div></button>
</div>

app/views/patients/new.html.erb
<%= render "form" %>